HelloHR/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from adminPanel import views


urlpatterns = [
    # path to admin page.
    path("admin/", admin.site.urls),
    # --------------- FRONTEND -------------- |
    # path to webpages.
    path('', include('webpages.urls')),
    # path to adminPanel.
    path('hellohr/', include('adminPanel.urls')),
    # path to user login.
    path('doLogin/', views.doLogin, name='user-login'),
    # path to user logout. 
    path('user_logout/', views.user_logout, name='user-logout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminPanel/urls.py
from django.urls import path
from . import freelancerViews, views, adminViews, hrViews, staffViews, freelancerViews


app_name = 'adminPanel'

urlpatterns = [
    # ==========================ADMIN-URL-PATH============================== |
    # ---------------------------- FRONTEND -------------------------------- |

	# path to dashboard page.
	path('admin/dashboard',adminViews.dashboard, name='admin-dashboard'),
    # path to login page.
	path('login/',views.login_page, name='login'),
    # path to admin change password.
    path('admin/change/password', views.change_password, name='change-password'),
    # path to match old password.
    path('admin/update/password', views.update_new_password, name='update-password'),
    # path to create CompanyHR account page.
    path('admin/create/companyHR',adminViews.add_company_hr, name='add-company-hr'),
    # path to manage CompanyHR account page.
    path('admin/manage/companyHR', adminViews.manage_company_hr, name='manage-compay-hr'),
    # path to update CompanyHR account page.
    path('admin/update/companyHR/<str:hr_id>', adminViews.update_company_hr, name='update-company-hr'),
    # path to create Staff account page.
    path('admin/create/staff',adminViews.add_staff, name='add-staff'),
    # path to manage Staff account page.
    path('admin/manage/staff', adminViews.manage_staff, name='manage-staff'),
    # path to update Staff account page.
    path('admin/update/staff/<str:staff_id>', adminViews.update_staff, name='update-staff'),
    # path to create Freelancer account page.
    path('admin/create/freelancer',adminViews.add_freelancer, name='add-freelancer'),
    # path to manage Freelancer account page.
    path('admin/manage/freelance', adminViews.manage_freelancer, name='manage-freelancer'),
    # path to update Freelancer account page.
    path('admin/update/freelancer/<str:freelancer_id>', adminViews.update_freelancer, name='update-freelancer'),
    # path to add Candidate page.
    path('admin/candidate/add', adminViews.add_candidate, name='add-candidate'),
    # path to manage candidate page.
    path('admin/manage/candidate', adminViews.manage_candidate, name='manage-candidate'),
    # path to view user profile page.
    path('admin/profile', adminViews.user_profile, name='admin-profile'),

    # ---------------------------- BACKEND -------------------------------- |

    # path to match old password.
    path('admin/match/password', views.match_old_password, name='match-password'),
    # path to save update password.
    path('admin/save/update/password', views.update_save_new_password, name='update-save-password'),
    # path to save CompanyHR account.
    path('admin/save/companyHR', adminViews.save_company_hr, name='save-company-hr'),
    # path to save update CompanyHR account.
    path('admin/save/update/companyHR', adminViews.save_update_company_hr, name='save-update-company-hr'),
    # path to delete CompanyHR account.
    path('admin/delete/companyHR/<str:hr_id>', adminViews.soft_delete_company_hr, name='delete-company-hr'),
    # path to save Staff account.
    path('admin/save/staff', adminViews.save_staff, name='save-staff'),
    # path to save update Staff account.
    path('admin/save/update/staff', adminViews.save_update_staff, name='save-update-staff'),
    # path to delete Staff account.
    path('admin/delete/staff/<str:staff_id>', adminViews.soft_delete_staff, name='delete-staff'),
    # path to save Freelancer account.
    path('admin/save/freelancer', adminViews.save_freelancer, name='save-freelancer'),
    # path to save update Freelancer account.
    path('admin/save/update/freelancer', adminViews.save_update_freelancer, name='save-update-freelancer'),
    # path to delete Freelancer account.
    path('admin/delete/freelancer/<str:freelancer_id>', adminViews.soft_delete_freelancer, name='delete-freelancer'),

    # ===========================HR-URL-PATH=============================== |
    # --------------------------- FRONTEND -------------------------------- |

    # path to dashboard page.
	path('hr/dashboard',hrViews.dashboard, name='hr-dashboard'),
    # path to candidate detail.
    path('hr/candidate/detail',hrViews.candidate_detail, name='hr-candidate-detail'),
    # path to manage candidate.
    path('hr/candidate/manage',hrViews.candidate_manage, name='hr-candidate-manage'),
    # path to selecte candidate.
    path('hr/candidate/selected',hrViews.candidate_selected, name='hr-candidate-selected'),
    # path to reject candidate.
    path('hr/candidate/rejected',hrViews.candidate_rejected, name='hr-candidate-rejected'),
    # path to change hr password.
    path('hr/change/password', hrViews.change_password, name='hr-change-password'),
    # path to update hr password.
    path('hr/update/password', hrViews.update_new_password, name='hr-update-password'),

    # ---------------------------- BACKEND -------------------------------- |

    # path to match hr old password.
    path('hr/match/password', hrViews.match_old_password, name='hr-match-password'),
    # path to save update hr password.
    path('hr/save/update/password', hrViews.update_save_new_password, name='hr-update-save-password'),


    # ==========================STAFF-URL-PATH============================= |
    # ---------------------------- FRONTEND ------------------------------- |

    # path to dashboard page.
	path('staff/dashboard',staffViews.dashboard, name='staff-dashboard'),
    # path to change staff password.
    path('staff/change/password', staffViews.change_password, name='staff-change-password'),
    # path to update staff password.
    path('staff/update/password', staffViews.update_new_password, name='staff-update-password'),
    # path to candidate submission page.
	path('staff/candidate/submission',staffViews.candidate_submission, name='staff-candidate-submission'),


    # ---------------------------- BACKEND -------------------------------- |

    # path to match staff old password.
    path('staff/match/password', staffViews.match_old_password, name='staff-match-password'),
    # path to save update staff password.
    path('staff/save/update/password', staffViews.update_save_new_password, name='staff-update-save-password'),

    # ========================FREELANCER-URL-PATH========================== |
    # ---------------------------- FRONTEND ------------------------------- |

    # path to dashboard page.
	path('freelancer/dashboard',freelancerViews.dashboard, name='freelancer-dashboard'),
    # path to change freelancer password.
    path('freelancer/change/password', freelancerViews.change_password, name='freelancer-change-password'),
    # path to update freelancer password.
    path('freelancer/update/password', freelancerViews.update_new_password, name='freelancer-update-password'),
    # path to candidate submission.
	path('freelancer/candidate/submission',freelancerViews.candidate_submission, name='freelancer-candidate-submission'),

    # ---------------------------- BACKEND -------------------------------- |

    # path to match freelancer old password.
    path('freelancer/match/password', freelancerViews.match_old_password, name='freelancer-match-password'),
    # path to save update freelancer password.
    path('freelancer/save/update/password', freelancerViews.update_save_new_password, name='freelancer-update-save-password'),

]

templates/hr-panel/candidate-manage.html
{% extends 'hr-panel/index.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static './css/admin/pagination.css' %}">
    <style>
        .table-fixed{
  width: 100%;
  background-color: #f3f3f3;
  tbody{
    height:200px;
    overflow-y:auto;
    width: 100%;
    }
  thead,tbody,tr,td,th{
    display:block;
  }
  tbody{
    td{
      float:left;
    }
  }
  thead {
    tr{
      th{
        float:left;
       background-color: #f39c12;
       border-color:#e67e22;
      }
    }
  }
}

    </style>
{% endblock %}

{% block content %}
<div class="app-main__inner">
    <div class="app-page-title p-0 m-0">
        <div class="row">
            <h4 class="col-md-6">Candidate Filter Search</h4>
         <!-- Breadcrumb -->
         <nav aria-label="breadcrumb" class="col-md-6 float-right">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="index.html">Home</a></li>
              <li class="breadcrumb-item"><a href="javascript:void(0)">User</a></li>
              <li class="breadcrumb-item active" aria-current="page">User Profile</li>
            </ol>
          </nav>
          <!-- /Breadcrumb -->
        </div>
        
    </div>
    <div class="row">
        <form class="row col-md-12">
        <div class="col-md-6 col-xl-4">
            <div class="form-group">
                <input name="candidate_name" type="text" class="form-control" placeholder="Candidate Name" />
            </div>
        </div>
        <div class="col-md-6 col-xl-4">
            <div class="form-group">
                <input name="candidate_name" type="text" class="form-control" placeholder="Candidate Email" />
            </div>
        </div>
        
        <div class="col-md-6 col-xl-4">
            <div class="form-group">
                <input name="candidate_name" type="text" class="form-control" placeholder="Candidate Username" />
            </div>
        </div>
        <div class="col-md-6 col-xl-4">
            <div class="form-group">
                <select name="status" id="" class="form-control">
                    <option value="selected">Selected</option>
                    <option value="rejected">Rejected</option>
                </select>
            </div>
        </div>
        <div class="col-md-6 col-xl-4">
            <div class="form-group date" data-provide="datepicker">
                <input type="date" data-provide="datepicker" class="form-control">
                <div class="input-group-addon">
                    <span class="glyphicon glyphicon-th"></span>
                </div>
            </div>
        </div>
        <div class="d-lg-block col-md-6 col-xl-4">
            <div class="form-group d-flex">
                <button type="submit" class="btn-flat btn btn-primary form-btn w-50">Search</button>
                <button type="reset" class="btn-flat btn btn-danger form-btn w-50">Reset</button>
            </div>
        </div>
    </form>
    </div>
    
    <div class="row">
        <div class="col-md-6 col-xl-4">
            <div class="card mb-3 widget-content bg-midnight-bloom">
                <div class="widget-content-wrapper text-white">
                    <div class="widget-content-left">
                        <div class="widget-heading">Total Candidate</div>
                        <div class="widget-subheading">Last year count</div>
                    </div>
                    <div class="widget-content-right">
                        <div class="widget-numbers text-white"><span>196</span></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-xl-4">
            <div class="card mb-3 widget-content bg-arielle-smile">
                <div class="widget-content-wrapper text-white">
                    <div class="widget-content-left">
                        <div class="widget-heading">Selected Candidate</div>
                        <div class="widget-subheading">Total number of selected candidate</div>
                    </div>
                    <div class="widget-content-right">
                        <div class="widget-numbers text-white"><span>568</span></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-xl-4">
            <div class="card mb-3 widget-content bg-grow-early">
                <div class="widget-content-wrapper text-white">
                    <div class="widget-content-left">
                        <div class="widget-heading">Rejected Candidate</div>
                        <div class="widget-subheading">Total number of rejected candidate</div>
                    </div>
                    <div class="widget-content-right">
                        <div class="widget-numbers text-white"><span>46</span></div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="main-card mb-3 card">
                <div class="table-responsive">
                    <table class="align-middle mb-0 table table-borderless table-striped table-hover">
                        <thead>
                            <tr class="badge-warning">
                                <th class="text-center">SL No</th>
                                <th class="text-center">First Name</th>
                                <th class="text-center">Last Name</th>
                                <th class="text-center">User email</th>
                                <th class="text-center">Username</th>
                                <th class="text-center">Login ID</th>
                                <th class="text-center">Status</th>
                                <th class="text-center">Address</th>
                                <th class="text-center">Registered</th>
                                <th class="text-center">Last Login</th>
                                <th class="text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody class="overflow-auto">
                            <tr>
                                <td class="text-center text-muted p-0">01</td>
                                <td class="text-center p-0">
                                    <div class="widget-content p-0">
                                        <div class="widget-content-wrapper">
                                            <div class="widget-content-left mr-3">
                                                <div class="widget-content-left">
                                                    <img width="40" class="rounded-circle"
                                                        src="assets/images/avatars/4.jpg" alt="">
                                                </div>
                                            </div>
                                            <div class="widget-content-left flex2">
                                                <div class="widget-heading">Koushik</div>
                                                
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td class="text-center p-0">Hait</td>
                                <td class="text-center p-0">
                                    koushikhait49@gmail.com
                                </td>
                                <td class="text-center p-0">koushikhait</td>
                                <td class="text-center p-0 text-danger">koushikhait49@gmail.com</td>
                                <td class="text-center p-0 "><div class="badge badge-warning">Rejected</div></td>
                                <td class="text-center p-0">kashinathpur</td>
                                <td class="text-center p-0">Yes</td>
                                <td class="text-center p-0">12/12/12</td>
                                <td class="text-center p-0">
                                    <div class="d-block text-center">
                                        <button class="btn-flat btn-xs btn btn-primary btn-sm"><a class="text-white" href="{% url 'adminPanel:hr-candidate-detail' %}">Candidate Details</a></button>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="pagination_rounded">
                    <ul>
                        <li>
                            <a href="#" class="prev"> <i class="fa fa-angle-left" aria-hidden="true"></i> Prev </a>
                        </li>
                        <li><a href="#">1</a>
                        </li>
                        <li class="hidden-xs"><a href="#">2</a>
                        </li>
                        <li class="hidden-xs"><a href="#">3</a>
                        </li>
                        <li class="hidden-xs"><a href="#">4</a>
                        </li>
                        <li class="hidden-xs"><a href="#">5</a>
                        </li>
                        <li class="visible-xs"><a href="#">...</a>
                        </li>
                        <li><a href="#">6</a>
                        </li>
                        <li><a href="#" class="next"> Next <i class="fa fa-angle-right" aria-hidden="true"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/hr-panel/candidate-rejected.html
{% extends 'hr-panel/index.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static './css/admin/pagination.css' %}">
    <style>
        .table-fixed{
  width: 100%;
  background-color: #f3f3f3;
  tbody{
    height:200px;
    overflow-y:auto;
    width: 100%;
    }
  thead,tbody,tr,td,th{
    display:block;
  }
  tbody{
    td{
      float:left;
    }
  }
  thead {
    tr{
      th{
        float:left;
       background-color: #f39c12;
       border-color:#e67e22;
      }
    }
  }
}

    </style>
{% endblock %}

{% block content %}
<div class="app-main__inner">
    <div class="app-page-title p-0 m-0">
        <div class="row">
            <h4 class="col-md-6">Candidate Filter Search</h4>
         <!-- Breadcrumb -->
         <nav aria-label="breadcrumb" class="col-md-6 float-right">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="index.html">Home</a></li>
              <li class="breadcrumb-item"><a href="javascript:void(0)">User</a></li>
              <li class="breadcrumb-item active" aria-current="page">User Profile</li>
            </ol>
          </nav>
          <!-- /Breadcrumb -->
        </div>
        
    </div>
    <div class="row">
        <form class="row col-md-12">
        <div class="col-md-6 col-xl-4">
            <div class="form-group">
                <input name="candidate_name" type="text" class="form-control" placeholder="Candidate Name" />
            </div>
        </div>

        <div class="col-md-6 col-xl-4">
            <div class="form-group">
                <select name="status" id="" class="form-control">
                    <option value="selected">Selected</option>
                    <option value="rejected">Rejected</option>
                </select>
            </div>
        </div>
        <div class="col-md-6 col-xl-4">
            <div class="form-group date" data-provide="datepicker">
                <input type="date" data-provide="datepicker" class="form-control">
                <div class="input-group-addon">
                    <span class="glyphicon glyphicon-th"></span>
                </div>
            </div>
        </div>
        
    </form>
    </div>
    
    <div class="row">
        <div class="col-md-6 col-xl-4">
            <div class="card mb-3 widget-content bg-midnight-bloom">
                <div class="widget-content-wrapper text-white">
                    <div class="widget-content-left">
                        <div class="widget-heading">Total Candidate</div>
                        <div class="widget-subheading">Last year count</div>
                    </div>
                    <div class="widget-content-right">
                        <div class="widget-numbers text-white"><span>196</span></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-xl-4">
            <div class="card mb-3 widget-content bg-arielle-smile">
                <div class="widget-content-wrapper text-white">
                    <div class="widget-content-left">
                        <div class="widget-heading">Selected Candidate</div>
                        <div class="widget-subheading">Total number of selected candidate</div>
                    </div>
                    <div class="widget-content-right">
                        <div class="widget-numbers text-white"><span>568</span></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-xl-4">
            <div class="card mb-3 widget-content bg-grow-early">
                <div class="widget-content-wrapper text-white">
                    <div class="widget-content-left">
                        <div class="widget-heading">Rejected Candidate</div>
                        <div class="widget-subheading">Total number of rejected candidate</div>
                    </div>
                    <div class="widget-content-right">
                        <div class="widget-numbers text-white"><span>46</span></div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="main-card mb-3 card">
                <div class="table-responsive">
                    <table class="align-middle mb-0 table table-borderless table-striped table-hover">
                        <thead>
                            <tr class="badge-warning">
                                <th class="text-center">SL No</th>
                                <th class="text-center">First Name</th>
                                <th class="text-center">Last Name</th>
                                <th class="text-center">User email</th>
                                <th class="text-center">Username</th>
                                
                                <th class="text-center">Status</th>
                                <th class="text-center">Address</th>
                                <th class="text-center">Registered</th>
                                <th class="text-center">Last Login</th>
                                <th class="text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody class="overflow-auto">
                            <tr>
                                <td class="text-center text-muted p-0">01</td>
                                <td class="text-center p-0">
                                    <div class="widget-content p-0">
                                        <div class="widget-content-wrapper">
                                            <div class="widget-content-left mr-3">
                                                <div class="widget-content-left">
                                                    <img width="40" class="rounded-circle"
                                                        src="assets/images/avatars/4.jpg" alt="">
                                                </div>
                                            </div>
                                            <div class="widget-content-left flex2">
                                                <div class="widget-heading">Koushik</div>
                                                
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td class="text-center p-0">Hait</td>
                                <td class="text-center p-0">
                                    koushikhait49@gmail.com
                                </td>
                                <td class="text-center p-0">koushikhait</td>
                                
                                <td class="text-center p-0 "><div class="badge badge-warning">Rejected</div></td>
                                <td class="text-center p-0">kashinathpur</td>
                                <td class="text-center p-0">Yes</td>
                                <td class="text-center p-0">12/12/12</td>
                                <td class="text-center p-0">
                                    <div class="d-block text-center">
                                        <button class="btn-flat btn-xs btn btn-primary btn-sm"><a class="text-white" href="{% url 'adminPanel:hr-candidate-detail' %}">View Details</a></button>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="pagination_rounded">
                    <ul>
                        <li>
                            <a href="#" class="prev"> <i class="fa fa-angle-left" aria-hidden="true"></i> Prev </a>
                        </li>
                        <li><a href="#">1</a>
                        </li>
                        <li class="hidden-xs"><a href="#">2</a>
                        </li>
                        <li class="hidden-xs"><a href="#">3</a>
                        </li>
                        <li class="hidden-xs"><a href="#">4</a>
                        </li>
                        <li class="hidden-xs"><a href="#">5</a>
                        </li>
                        <li class="visible-xs"><a href="#">...</a>
                        </li>
                        <li><a href="#">6</a>
                        </li>
                        <li><a href="#" class="next"> Next <i class="fa fa-angle-right" aria-hidden="true"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/hr-panel/change-password.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>HelloHR | Change Password </title>

  <style>
    .mainDiv {
      display: flex;
      min-height: 100%;
      align-items: center;
      justify-content: center;
      background-color: #f9f9f9;
      font-family: 'Open Sans', sans-serif;
    }

    .cardStyle {
      width: 500px;
      border-color: white;
      background: #fff;
      padding: 36px 0;
      border-radius: 4px;
      margin: 30px 0;
      box-shadow: 0px 0 2px 0 rgba(0, 0, 0, 0.25);
    }

    #signupLogo {
      max-height: 100px;
      margin: auto;
      display: flex;
      flex-direction: column;
    }

    .formTitle {
      font-weight: 600;
      margin-top: 20px;
      color: #2F2D3B;
      text-align: center;
    }

    .inputLabel {
      font-size: 12px;
      color: #555;
      margin-bottom: 6px;
      margin-top: 24px;
    }

    .inputDiv {
      width: 70%;
      display: flex;
      flex-direction: column;
      margin: auto;
    }

    input {
      height: 40px;
      font-size: 16px;
      border-radius: 4px;
      border: none;
      border: solid 1px #ccc;
      padding: 0 11px;
    }

    input:disabled {
      cursor: not-allowed;
      border: solid 1px #eee;
    }

    .buttonWrapper {
      margin-top: 40px;
    }

    .submitButton {
      width: 70%;
      height: 40px;
      margin: auto;
      display: block;
      color: #fff;
      background-color: #065492;
      border-color: #065492;
      text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.12);
      box-shadow: 0 2px 0 rgba(0, 0, 0, 0.035);
      border-radius: 4px;
      font-size: 14px;
      cursor: pointer;
    }

    .submitButton:disabled,
    button[disabled] {
      border: 1px solid #cccccc;
      background-color: #cccccc;
      color: #666666;
    }

    #loader {
      position: absolute;
      z-index: 1;
      margin: -2px 0 0 10px;
      border: 4px solid #f3f3f3;
      border-radius: 50%;
      border-top: 4px solid #666666;
      width: 14px;
      height: 14px;
      -webkit-animation: spin 2s linear infinite;
      animation: spin 2s linear infinite;
    }

    @keyframes spin {
      0% {
        transform: rotate(0deg);
      }

      100% {
        transform: rotate(360deg);
      }
    }
  </style>
</head>

<body>
  <div class="mainDiv">
    <div class="cardStyle">
      <form action="/hellohr/hr/match/password" method="post" name="signupForm" id="signupForm">
        {% csrf_token %}
        <img src="" id="signupLogo" />

        <h2 class="formTitle">
          Change your account password
        </h2>
        <div class="inputDiv password-old">
          <label class="inputLabel " for="password">Current Password</label>
          <input type="password" id="password" name="old_password" required placeholder="Enter your current password">
        </div>
        <div class="row">
          <div class="input-group">
            {% if messages %}
            <div class="col-12">
              {% for message in messages %}
                  {% if message.tags == 'error' %}
                      <div class="alert alert-danger text-center" style="margin-top: 10px;">{{ message }}</div>
                  {% endif %}
                  <!-- {% if message.tags == 'success' %}
                      <div class="alert alert-success text-center" style="margin-top: 10px;">{{ message }}</div>
                  {% endif %} -->
              {% endfor %}
            </div>
            {% endif %}
          </div>
        </div>
        <div class="buttonWrapper password-old">
          <button type="submit" id="submitButton" onclick="validateSignupForm()"
            class="submitButton pure-button pure-button-primary">
            <span>Continue</span>
            <!-- <span id="loader"></span> -->
          </button>
        </div>
      </form>
    </div>
  </div>

  <script>
    var password_old = document.getElementsByClassName("password-old")
    var password_change = document.getElementsByClassName("password-change");



    // function validatePassword() {
    //   if(password.value != confirm_password.value) {
    //     confirm_password.setCustomValidity("Passwords Don't Match");
    //     return false;
    //   } else {
    //     confirm_password.setCustomValidity('');
    //     return true;
    //   }
    // }
  </script>
</body>

</html>