HelloHR/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from adminPanel import views


urlpatterns = [
    # path to admin page.
    path("admin/", admin.site.urls),
    # --------------- FRONTEND -------------- |
    # path to webpages.
    path('', include('webpages.urls')),
    # path to adminPanel.
    path('hellohr/', include('adminPanel.urls')),
    # path to user login.
    path('doLogin/', views.doLogin, name='user-login'),
    # path to user logout. 
    path('user_logout/', views.user_logout, name='user-logout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminPanel/urls.py
from django.urls import path
from . import freelancerViews, views, adminViews, hrViews, staffViews, freelancerViews


app_name = 'adminPanel'

urlpatterns = [
    # ==========================ADMIN-URL-PATH============================== |
    # ---------------------------- FRONTEND -------------------------------- |

	# path to dashboard page.
	path('admin/dashboard',adminViews.dashboard, name='admin-dashboard'),
    # path to login page.
	path('login/',views.login_page, name='login'),
    # path to admin change password.
    path('admin/change/password', views.change_password, name='change-password'),
    # path to match old password.
    path('admin/update/password', views.update_new_password, name='update-password'),
    # path to create CompanyHR account page.
    path('admin/create/companyHR',adminViews.add_company_hr, name='add-company-hr'),
    # path to manage CompanyHR account page.
    path('admin/manage/companyHR', adminViews.manage_company_hr, name='manage-compay-hr'),
    # path to update CompanyHR account page.
    path('admin/update/companyHR/<str:hr_id>', adminViews.update_company_hr, name='update-company-hr'),
    # path to create Staff account page.
    path('admin/create/staff',adminViews.add_staff, name='add-staff'),
    # path to manage Staff account page.
    path('admin/manage/staff', adminViews.manage_staff, name='manage-staff'),
    # path to update Staff account page.
    path('admin/update/staff/<str:staff_id>', adminViews.update_staff, name='update-staff'),
    # path to create Freelancer account page.
    path('admin/create/freelancer',adminViews.add_freelancer, name='add-freelancer'),
    # path to manage Freelancer account page.
    path('admin/manage/freelance', adminViews.manage_freelancer, name='manage-freelancer'),
    # path to update Freelancer account page.
    path('admin/update/freelancer/<str:freelancer_id>', adminViews.update_freelancer, name='update-freelancer'),
    # path to add Candidate page.
    path('admin/candidate/add', adminViews.add_candidate, name='add-candidate'),
    # path to manage candidate page.
    path('admin/manage/candidate', adminViews.manage_candidate, name='manage-candidate'),
    # path to view user profile page.
    path('admin/profile', adminViews.user_profile, name='admin-profile'),

    # ---------------------------- BACKEND -------------------------------- |

    # path to match old password.
    path('admin/match/password', views.match_old_password, name='match-password'),
    # path to save update password.
    path('admin/save/update/password', views.update_save_new_password, name='update-save-password'),
    # path to save CompanyHR account.
    path('admin/save/companyHR', adminViews.save_company_hr, name='save-company-hr'),
    # path to save update CompanyHR account.
    path('admin/save/update/companyHR', adminViews.save_update_company_hr, name='save-update-company-hr'),
    # path to delete CompanyHR account.
    path('admin/delete/companyHR/<str:hr_id>', adminViews.soft_delete_company_hr, name='delete-company-hr'),
    # path to save Staff account.
    path('admin/save/staff', adminViews.save_staff, name='save-staff'),
    # path to save update Staff account.
    path('admin/save/update/staff', adminViews.save_update_staff, name='save-update-staff'),
    # path to delete Staff account.
    path('admin/delete/staff/<str:staff_id>', adminViews.soft_delete_staff, name='delete-staff'),
    # path to save Freelancer account.
    path('admin/save/freelancer', adminViews.save_freelancer, name='save-freelancer'),
    # path to save update Freelancer account.
    path('admin/save/update/freelancer', adminViews.save_update_freelancer, name='save-update-freelancer'),
    # path to delete Freelancer account.
    path('admin/delete/freelancer/<str:freelancer_id>', adminViews.soft_delete_freelancer, name='delete-freelancer'),

    # ===========================HR-URL-PATH=============================== |
    # --------------------------- FRONTEND -------------------------------- |

    # path to dashboard page.
	path('hr/dashboard',hrViews.dashboard, name='hr-dashboard'),
    # path to candidate detail.
    path('hr/candidate/detail',hrViews.candidate_detail, name='hr-candidate-detail'),
    # path to manage candidate.
    path('hr/candidate/manage',hrViews.candidate_manage, name='hr-candidate-manage'),
    # path to selecte candidate.
    path('hr/candidate/selected',hrViews.candidate_selected, name='hr-candidate-selected'),
    # path to reject candidate.
    path('hr/candidate/rejected',hrViews.candidate_rejected, name='hr-candidate-rejected'),
    # path to change hr password.
    path('hr/change/password', hrViews.change_password, name='hr-change-password'),
    # path to update hr password.
    path('hr/update/password', hrViews.update_new_password, name='hr-update-password'),

    # ---------------------------- BACKEND -------------------------------- |

    # path to match hr old password.
    path('hr/match/password', hrViews.match_old_password, name='hr-match-password'),
    # path to save update hr password.
    path('hr/save/update/password', hrViews.update_save_new_password, name='hr-update-save-password'),


    # ==========================STAFF-URL-PATH============================= |
    # ---------------------------- FRONTEND ------------------------------- |

    # path to dashboard page.
	path('staff/dashboard',staffViews.dashboard, name='staff-dashboard'),
    # path to change staff password.
    path('staff/change/password', staffViews.change_password, name='staff-change-password'),
    # path to update staff password.
    path('staff/update/password', staffViews.update_new_password, name='staff-update-password'),
    # path to candidate submission page.
	path('staff/candidate/submission',staffViews.candidate_submission, name='staff-candidate-submission'),


    # ---------------------------- BACKEND -------------------------------- |

    # path to match staff old password.
    path('staff/match/password', staffViews.match_old_password, name='staff-match-password'),
    # path to save update staff password.
    path('staff/save/update/password', staffViews.update_save_new_password, name='staff-update-save-password'),

    # ========================FREELANCER-URL-PATH========================== |
    # ---------------------------- FRONTEND ------------------------------- |

    # path to dashboard page.
	path('freelancer/dashboard',freelancerViews.dashboard, name='freelancer-dashboard'),
    # path to change freelancer password.
    path('freelancer/change/password', freelancerViews.change_password, name='freelancer-change-password'),
    # path to update freelancer password.
    path('freelancer/update/password', freelancerViews.update_new_password, name='freelancer-update-password'),
    # path to candidate submission.
	path('freelancer/candidate/submission',freelancerViews.candidate_submission, name='freelancer-candidate-submission'),

    # ---------------------------- BACKEND -------------------------------- |

    # path to match freelancer old password.
    path('freelancer/match/password', freelancerViews.match_old_password, name='freelancer-match-password'),
    # path to save update freelancer password.
    path('freelancer/save/update/password', freelancerViews.update_save_new_password, name='freelancer-update-save-password'),

]

adminPanel/views.py
from django.shortcuts import render
from django.urls import reverse # Reverse the function url.
from django.http import HttpResponse, HttpResponseRedirect # Redirect the function urls
from django.contrib.auth import login, logout
from django.contrib import messages # Return messages.
from django.contrib.auth.decorators import login_required # Login required to access private pages.
from django.views.decorators.cache import cache_control # Destroy the section after logout.
from adminPanel.EmailBackEnd import EmailBackEnd # Used to login with user email ID.
from django.contrib.auth.hashers import check_password # Check logged-in user password.




# This function is used to user logged in page.
def login_page(request):
    return render(request, 'admin-panel/login.html')
    

# This function is used to get user logged in.
def doLogin(request):
    if request.method!="POST":
        return HttpResponse("<h2>Method Not Allowed</h2>")
    else:
        email=request.POST.get('email')
        password=request.POST.get('password')
        
        user=EmailBackEnd.authenticate(request, username=email, password=password)
        if user is not None:
            login(request,user)
            if user.user_type=="1":
                messages.success(request, email+" logged in successfully")
                return HttpResponseRedirect(reverse("adminPanel:admin-dashboard"))
            elif user.user_type=="2":
                messages.success(request, email+" logged in successfully")
                return HttpResponseRedirect(reverse("adminPanel:hr-dashboard"))
            elif user.user_type=="3":
                messages.success(request, email+" logged in successfully")
                return HttpResponseRedirect(reverse("adminPanel:staff-dashboard"))
            else:
                messages.success(request, email+" logged in successfully")
                return HttpResponseRedirect(reverse("adminPanel:freelancer-dashboard"))
        else:
            messages.error(request, 'Invalid Logged in details')
            return HttpResponseRedirect(reverse("adminPanel:login"))
    

# This function is used to user logged out.
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("adminPanel:login"))


# This function is used to change Admin password:
@login_required(login_url="adminPanel:login")
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def change_password(request):
    return render(request, 'admin-panel/change-password.html')


# This function is used to match admin password.
@login_required(login_url="adminPanel:login")
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def match_old_password(request):
    user = request.user
    print(user.password)
    if request.method == 'POST':
        old_password = request.POST['old_password']

    # Check if the current password is valid.
    if not check_password(old_password, user.password):
        messages.error(request, 'Old password is incorrect.')
        return HttpResponseRedirect(reverse('adminPanel:change-password'))
    
    return HttpResponseRedirect(reverse('adminPanel:update-password'))
    

# This function is used to update Admin password:
@login_required(login_url="adminPanel:login")
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def update_new_password(request):
    return render(request, 'admin-panel/match-password.html')
    

# This function to update save Admin new password:
@login_required(login_url="adminPanel:login")
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def update_save_new_password(request):
    user = request.user
    if request.method == 'POST':
        new_password = request.POST['new_password']
        new_confirm_password = request.POST['new_confirm_password']
        print(new_password)
        print(new_confirm_password)
        
        # Check if the new password and confirmation match.
        if new_password != new_confirm_password:
            messages.error(request, 'New password do not match.')
            return HttpResponseRedirect(reverse('adminPanel:update-password'))
        
        # Set the new password and update the session auth hash
        user.set_password(new_password)
        user.save()

        messages.success(request, 'Password changed successfully.')
        return HttpResponseRedirect(reverse('adminPanel:login'))
    

templates/admin-panel/freelancer/create-freelancer.html
{% extends 'admin-panel/index.html' %}
{% load static %}

{% block css %}
<style>
.pad-bg {
    background: #f8f8f8;
    padding: 40px 20px;
    border-radius: 5px;
    margin-top: 50px;
    margin-bottom: 50px;
    border: 1px solid #e5e5e5;
    h1 {
      padding-bottom: 30px;
      margin-top: 0;
      margin-bottom: 30px;
      border-bottom: 1px dashed #ccc;
    }
  }
</style>
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-2">
        <form method="POST" action="/hellohr/admin/save/freelancer" class="form-horizontal pad-bg">
          {% csrf_token %}
          <h1 class="text-center">Add Freelancer Account</h1>
          <div class="form-group row">
            <label for="" class="control-label col-sm-3 float-right">First Name</label>
            <div class="col-sm-9">
              <input type="text" class="form-control input-lg" name="first_name" placeholder="First name">
            </div>  
          </div>
          <div class="form-group row">
            <label for="" class="control-label col-sm-3 float-right">Last Name</label>
            <div class="col-sm-9">
              <input type="text" class="form-control input-lg" name="last_name" placeholder="Last name">
            </div>  
          </div>
          <div class="form-group row">
            <label for="" class="control-label col-sm-3 float-right">Username</label>
            <div class="col-sm-9">
              <input type="text" class="form-control input-lg" name="username" placeholder="Username">
            </div>  
          </div>
          <div class="form-group row">
            <label for="" class="control-label col-sm-3 float-right">Email</label>
            <div class="col-sm-9">
              <input type="email" class="form-control input-lg" name="email" placeholder="Email">
            </div>  
          </div>
          <div class="form-group row">
            <label for="" class="control-label col-sm-3 float-right">Mobile No.</label>
            <div class="col-sm-9">
              <input type="text" class="form-control input-lg" name="mobile_no" placeholder="Mobile No.">
            </div>  
          </div>
          <div class="form-group row">
            <label for="" class="control-label col-sm-3 float-right">Address</label>
            <div class="col-sm-9">
              <input type="text" class="form-control input-lg" name="address" placeholder="address">
            </div>  
          </div>
          <div class="form-group row">
            <label for="" class="control-label col-sm-3">Password</label>
            <div class="col-sm-9">
              <input type="password" class="form-control input-lg" name="password" placeholder="Password">
            </div>  
          </div>
          <div class="form-group row">
            <div class="col-sm-offset-3 col-sm-12 float-right">
              <button class="btn btn-dark btn-lg float-right">Submit</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

  {% endblock %}

{% block js %}

<script>

</script>

{% endblock %}

templates/admin-panel/freelancer/manage-freelancer.html
{% extends 'admin-panel/index.html' %}
{% load static %}

{% block content %}


<div class="app-main__inner">
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <span>MANAGE ALL <b>FREELACER ACCOUNT</b></span>
            </div>
            <div class="page-title-actions">
                <h5>Hii</h5>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-xl-4">
            <div class="card mb-3 widget-content bg-midnight-bloom">
                <div class="widget-content-wrapper text-white">
                    <div class="widget-content-left">
                        <div class="widget-heading">Total Orders</div>
                        <div class="widget-subheading">Last year expenses</div>
                    </div>
                    <div class="widget-content-right">
                        <div class="widget-numbers text-white"><span>1896</span></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-xl-4">
            <div class="card mb-3 widget-content bg-arielle-smile">
                <div class="widget-content-wrapper text-white">
                    <div class="widget-content-left">
                        <div class="widget-heading">Clients</div>
                        <div class="widget-subheading">Total Clients Profit</div>
                    </div>
                    <div class="widget-content-right">
                        <div class="widget-numbers text-white"><span>$ 568</span></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-xl-4">
            <div class="card mb-3 widget-content bg-grow-early">
                <div class="widget-content-wrapper text-white">
                    <div class="widget-content-left">
                        <div class="widget-heading">Followers</div>
                        <div class="widget-subheading">People Interested</div>
                    </div>
                    <div class="widget-content-right">
                        <div class="widget-numbers text-white"><span>46%</span></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="d-xl-none d-lg-block col-md-6 col-xl-4">
            <div class="card mb-3 widget-content bg-premium-dark">
                <div class="widget-content-wrapper text-white">
                    <div class="widget-content-left">
                        <div class="widget-heading">Products Sold</div>
                        <div class="widget-subheading">Revenue streams</div>
                    </div>
                    <div class="widget-content-right">
                        <div class="widget-numbers text-warning"><span>$14M</span></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="main-card mb-3 card">
                <div class="card-header">Active Users
                    <div class="btn-actions-pane-right">
                        <div role="group" class="btn-group-sm btn-group">
                            <button class="active btn btn-focus">Last Week</button>
                            <button class="btn btn-focus">All Month</button>
                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="align-middle mb-0 table table-borderless table-striped table-hover">
                        <thead>
                            <tr>
                                <th class="text-center">SL No</th>
                                <th class="text-center">First Name</th>
                                <th class="text-center">Last Name</th>
                                <th class="text-center">User email</th>
                                <th class="text-center">Username</th>
                                <th class="text-center">Login ID</th>
                                <th class="text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for frln in freelancers %}
                            <tr>
                                <td class="text-center text-muted p-0">{{ forloop.counter }}</td>
                                <td class="text-center p-0">
                                    <div class="widget-content p-0">
                                        <div class="widget-content-wrapper">
                                            <div class="widget-content-left mr-3">
                                                <div class="widget-content-left">
                                                    <img width="40" class="rounded-circle"
                                                        src="assets/images/avatars/4.jpg" alt="">
                                                </div>
                                            </div>
                                            <div class="widget-content-left flex2">
                                                <div class="widget-heading">{{ frln.admin.first_name }}</div>
                                                <!-- <div class="widget-subheading opacity-7">Web Developer</div> -->
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td class="text-center p-0">{{ frln.admin.last_name }}</td>
                                <td class="text-center p-0">
                                    {{ frln.freelancer_email }}
                                </td>
                                <td class="text-center p-0">{{ frln.admin.username }}</td>
                                <td class="text-center p-0 text-danger">{{ frln.admin.email }}</td>
                                <td class="text-center p-0">
                                    <div class="d-block text-center">
                                        <button class="btn-icon btn-icon-only btn btn-outline-danger"><a href="{% url 'adminPanel:delete-freelancer' frln.admin.id %}">Delete</a></button>
                                        <button class="btn-wide btn btn-success"><a href="{% url 'adminPanel:update-freelancer' frln.admin.id %}">Edit</a></button>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

templates/admin-panel/freelancer/update-freelancer.html
{% extends 'admin-panel/index.html' %}
{% load static %}

{% block css %}
<style>
.pad-bg {
    background: #f8f8f8;
    padding: 40px 20px;
    border-radius: 5px;
    margin-top: 50px;
    margin-bottom: 50px;
    border: 1px solid #e5e5e5;
    h1 {
      padding-bottom: 30px;
      margin-top: 0;
      margin-bottom: 30px;
      border-bottom: 1px dashed #ccc;
    }
  }
</style>
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-2">
        <form method="POST" action="/hellohr/admin/save/update/freelancer" class="form-horizontal pad-bg">
          {% csrf_token %}
          <h1 class="text-center">Update Freelancer Account</h1>
          <div class="form-group row">
            <label for="" class="control-label col-sm-3 float-right">First Name</label>
            <div class="col-sm-9">
              <input name="first_name" type="text" placeholder="First Name" required class="form-control input-lg" value={{freelancer.admin.first_name}}>
            </div>  
              <input type="hidden" name="freelancer_id" value={{freelancer.admin.id}}>
          </div>
          <div class="form-group row">
            <label for="" class="control-label col-sm-3 float-right">Last Name</label>
            <div class="col-sm-9">
              <input name="last_name" type="text" class="form-control input-lg" placeholder="Last Name" required value={{freelancer.admin.last_name}}>
            </div>  
          </div>
          <div class="form-group row">
            <label for="" class="control-label col-sm-3 float-right">Login ID</label>
            <div class="col-sm-9">
              <input type="email" class="form-control input-lg" value={{freelancer.admin.email}} disabled>
            </div>  
          </div>
          <div class="form-group row">
            <label for="" class="control-label col-sm-3 float-right">Username</label>
            <div class="col-sm-9">
              <input name="username" type="text" class="form-control input-lg" placeholder="UserName" required value={{freelancer.admin.username}}>
            </div>  
          </div>
          <div class="form-group row">
            <label for="" class="control-label col-sm-3 float-right">Email</label>
            <div class="col-sm-9">
              <input name="email" type="email" class="form-control input-lg" placeholder="Email Address" required value={{freelancer.freelancer_email}}>
            </div>  
          </div>
          <div class="form-group row">
            <label for="" class="control-label col-sm-3 float-right">Mobile No.</label>
            <div class="col-sm-9">
              <input name="mobile_no" type="text" class="form-control input-lg" placeholder="Mobile Number" required value={{freelancer.mobile_no}}>
            </div>  
          </div>
          <div class="form-group row">
            <label for="" class="control-label col-sm-3 float-right">Address</label>
            <div class="col-sm-9">
              <input name="address" type="text" class="form-control input-lg" placeholder="Address" required value={{freelancer.address}}>
            </div>  
          </div>
          <div class="form-group row">
            <label for="" class="control-label col-sm-3 float-right">Password</label>
            <div class="col-sm-9">
              <input name="password" type="password" class="form-control input-lg" placeholder="password" required value={{freelancer.admin.password}}>
            </div>  
          </div>
          <div class="form-group row">
            <div class="col-sm-offset-3 col-sm-12 float-right">
              <button type="submit" class="btn btn-dark btn-lg float-right">Update</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

  {% endblock %}

{% block js %}

<script>

</script>

{% endblock %}